require("after.core.treesitter")
require("after.core.nvim-tree")
require("after.core.telescope")
require("after.core.easymotion")
require("after.core.mason")
require("after.core.lualine")
require("after.core.resize")
require("after.core.snipets")
